config:
    type: politics
    subtype: initiatives
    agents: parties
    categorization: promesas-electorales-estado
    scope: international # internationa, national, regional or local
    organization: europe
    institution: europe
    lang: es
    draft: true
    
context:
    name: "Europa: Legislatura IX"
    description: Seguimiento de las políticas y actividad legislativa de la Unión Europea.
    elections: 2019-05-26
    from: 2019-07-02 
    goverment_type: coalition
    goverment_parties: [PSOE, UNIDAS PODEMOS]
    sources:
        - https://www.lamoncloa.gob.es/gobierno/gobiernosporlegislaturas/Paginas/xiv_legislatura.aspx
        - https://www.congreso.es/indice-de-iniciativas



