_id: 8973701e-4795-4195-ba8b-f64637e7e9fa
title: Proposición no de Ley relativa a la derogación urgente de ciertos aspectos de la reforma laboral referidos a las condiciones del despido colectivo. (161/000938)
date: 2021-06-01
record: 161/002736
trigger: [parlament-initiative] # international-treaty, europe-directive, popular-initiative, parlament-initiative (wheter congress or senate), goverment-initiative
parlament_groups: Grupo Parlamentario Plural
parties: [BNG, ]
status: "rechazado"
sources:
  -
    title: "Congreso: Expediente"
    url: https://www.congreso.es/busqueda-de-iniciativas?p_p_id=iniciativas&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_iniciativas_mode=mostrarDetalle&_iniciativas_legislatura=XIV&_iniciativas_id=161/002736
  -
    title: "Congreso: Publicación contenido"
    url: https://www.congreso.es/busqueda-de-publicaciones?p_p_id=publicaciones&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_publicaciones_mode=mostrarTextoIntegro&_publicaciones_legislatura=XIV&_publicaciones_id_texto=(BOCG-14-D-292.CODI.)#(P%C3%A1gina32)

