config:
    type: politics-promises-by-party
    categorization: promesas-politica-estatal
    scope: national # international, national, regional or local
    country: spain # if scope is "international" then instead of "country:" use "organization:"
    institution: congreso
    lang: es
    draft: false
    group_by: legislature
context:
    name: Legislatura XV
    description: Control sobre el grado de cumplimiento de los compromisos electorales de los partidos políticos y congresistas.
    election_type: generales 
    from: "2023-07-23"
    goverment_type:
    goverment_parties:
    sources:
        - https://www.lamoncloa.gob.es/gobierno/gobiernosporlegislaturas/Paginas/xiv_legislatura.aspx
        - https://www.congreso.es/indice-de-iniciativas
parties:
    -
        name: PSOE
        seats: 120
        program_doc: 
            - psoe_2019_10N.pdf
            - 2019-coalicion-progresista.pdf
        position: government
    -
        name: PP
        seats: 89
        program_doc: pp_2019_10N.pdf
        position: opposition
    -
        name: VOX
        seats: 52
        program_doc: vox_2019_10N.pdf
        position: opposition
    -
        name: UNIDAS PODEMOS
        aliance_of: [IU, Podemos]
        seats: 26
        program_doc: 
            - podemos_2019_10N.pdf
            - iu_2019_10N.
            - Coalición-progresista.pdf
        position: government
    -
        name: ERC
        seats: 13
        position: opposition
    -
        name: Cs
        seats: 10
        program_doc: ciudadanos_2019_10N.pdf
        position: opposition
    -
        name: JxCat
        seats: 8
        position: opposition
    -
        name: En Comú Podem
        seats: 7
        position: government
    -
        name: PNV
        seats: 6
        position: opposition
    -
        name: Eh Bildu
        seats: 5
        position: opposition
    -
        name: MÁS PAÍS EQUO
        seats: 2
        position: opposition
    -
        name: CUP-PR
        seats: 2
        position: opposition
    -
        name: CC-NC
        seats: 2
        position: opposition
    -
        name: NA+
        seats: 2
        position: opposition
    -
        name: En Común Unidas Podemos
        seats: 2
        position: government
    -
        name: BNG
        seats: 1
        position: opposition
    -
        name: PRC
        seats: 1
        position: opposition
    -
        name: ¡TERUEL EXISTE!
        seats: 1
        position: opposition    


