_id: 6ac8acf8-e2c4-4c72-89d5-496af51b64a0
parent_initiative: 9cda8a7a-09db-4a6c-bfc7-3f6d80f73d46
title: Moción consecuencia de interpelación urgente sobre las razones que tiene el Gobierno para modificar la reforma laboral. (173/000064)
date: 2022-03-25
record: 173/000064
trigger: [parlament-initiative]
type: motion
parlament_groups: Grupo Parlamentario Popular
parties: [PP]
votes: sesion91votacion46
status: "rechazada"
intervenciones: https://www.congreso.es/busqueda-de-intervenciones?p_p_id=intervenciones&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_intervenciones_mode=view&_intervenciones_legislatura=XIV&_intervenciones_id_iniciativa=173/000064
sources:
  -
    title: "Congreso: Expediente"
    url: https://www.congreso.es/busqueda-de-iniciativas?p_p_id=iniciativas&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_iniciativas_mode=mostrarDetalle&_iniciativas_legislatura=XIV&_iniciativas_id=173/000064
  -
    title: "Congreso: Publicación iniciativa"
    url: https://www.congreso.es/busqueda-de-publicaciones?p_p_id=publicaciones&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_publicaciones_mode=mostrarTextoIntegro&_publicaciones_legislatura=XIV&_publicaciones_id_texto=(BOCG-14-D-260.CODI.)#(P%C3%A1gina18)